services:
  - type: web
    name: kuriftu-hospitality-admin
    env: node
    buildCommand: npm install && npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
